// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf3.proto

package top.limitart.net;

public final class ProtobufMessageDemo {
  private ProtobufMessageDemo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface Demo1OrBuilder extends
      // @@protoc_insertion_point(interface_extends:Demo1)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     */
    String getName();
    /**
     * <code>string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code Demo1}
   */
  public  static final class Demo1 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Demo1)
      Demo1OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Demo1.newBuilder() to construct.
    private Demo1(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Demo1() {
      name_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Demo1(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtobufMessageDemo.internal_static_Demo1_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtobufMessageDemo.internal_static_Demo1_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Demo1.class, Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile Object name_;
    /**
     * <code>string name = 1;</code>
     */
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Demo1)) {
        return super.equals(obj);
      }
      Demo1 other = (Demo1) obj;

      boolean result = true;
      result = result && getName()
          .equals(other.getName());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Demo1 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Demo1 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Demo1 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Demo1 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Demo1 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Demo1 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Demo1 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Demo1 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Demo1 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Demo1 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Demo1 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Demo1 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Demo1 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Demo1}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Demo1)
        Demo1OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtobufMessageDemo.internal_static_Demo1_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtobufMessageDemo.internal_static_Demo1_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Demo1.class, Builder.class);
      }

      // Construct using top.limitart.net.ProtobufMessageDemo.Demo1.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        name_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtobufMessageDemo.internal_static_Demo1_descriptor;
      }

      @Override
      public Demo1 getDefaultInstanceForType() {
        return Demo1.getDefaultInstance();
      }

      @Override
      public Demo1 build() {
        Demo1 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Demo1 buildPartial() {
        Demo1 result = new Demo1(this);
        result.name_ = name_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Demo1) {
          return mergeFrom((Demo1)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Demo1 other) {
        if (other == Demo1.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Demo1 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Demo1) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object name_ = "";
      /**
       * <code>string name = 1;</code>
       */
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Demo1)
    }

    // @@protoc_insertion_point(class_scope:Demo1)
    private static final Demo1 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Demo1();
    }

    public static Demo1 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Demo1>
        PARSER = new com.google.protobuf.AbstractParser<Demo1>() {
      @Override
      public Demo1 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Demo1(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Demo1> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Demo1> getParserForType() {
      return PARSER;
    }

    @Override
    public Demo1 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface Demo2OrBuilder extends
      // @@protoc_insertion_point(interface_extends:Demo2)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Demo1 demo1 = 1;</code>
     */
    java.util.List<Demo1>
        getDemo1List();
    /**
     * <code>repeated .Demo1 demo1 = 1;</code>
     */
    Demo1 getDemo1(int index);
    /**
     * <code>repeated .Demo1 demo1 = 1;</code>
     */
    int getDemo1Count();
    /**
     * <code>repeated .Demo1 demo1 = 1;</code>
     */
    java.util.List<? extends Demo1OrBuilder>
        getDemo1OrBuilderList();
    /**
     * <code>repeated .Demo1 demo1 = 1;</code>
     */
    Demo1OrBuilder getDemo1OrBuilder(
            int index);

    /**
     * <code>int32 id = 2;</code>
     */
    int getId();
  }
  /**
   * Protobuf type {@code Demo2}
   */
  public  static final class Demo2 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Demo2)
      Demo2OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Demo2.newBuilder() to construct.
    private Demo2(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Demo2() {
      demo1_ = java.util.Collections.emptyList();
      id_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Demo2(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                demo1_ = new java.util.ArrayList<Demo1>();
                mutable_bitField0_ |= 0x00000001;
              }
              demo1_.add(
                  input.readMessage(Demo1.parser(), extensionRegistry));
              break;
            }
            case 16: {

              id_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          demo1_ = java.util.Collections.unmodifiableList(demo1_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtobufMessageDemo.internal_static_Demo2_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtobufMessageDemo.internal_static_Demo2_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Demo2.class, Builder.class);
    }

    private int bitField0_;
    public static final int DEMO1_FIELD_NUMBER = 1;
    private java.util.List<Demo1> demo1_;
    /**
     * <code>repeated .Demo1 demo1 = 1;</code>
     */
    public java.util.List<Demo1> getDemo1List() {
      return demo1_;
    }
    /**
     * <code>repeated .Demo1 demo1 = 1;</code>
     */
    public java.util.List<? extends Demo1OrBuilder>
        getDemo1OrBuilderList() {
      return demo1_;
    }
    /**
     * <code>repeated .Demo1 demo1 = 1;</code>
     */
    public int getDemo1Count() {
      return demo1_.size();
    }
    /**
     * <code>repeated .Demo1 demo1 = 1;</code>
     */
    public Demo1 getDemo1(int index) {
      return demo1_.get(index);
    }
    /**
     * <code>repeated .Demo1 demo1 = 1;</code>
     */
    public Demo1OrBuilder getDemo1OrBuilder(
        int index) {
      return demo1_.get(index);
    }

    public static final int ID_FIELD_NUMBER = 2;
    private int id_;
    /**
     * <code>int32 id = 2;</code>
     */
    public int getId() {
      return id_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < demo1_.size(); i++) {
        output.writeMessage(1, demo1_.get(i));
      }
      if (id_ != 0) {
        output.writeInt32(2, id_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < demo1_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, demo1_.get(i));
      }
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, id_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Demo2)) {
        return super.equals(obj);
      }
      Demo2 other = (Demo2) obj;

      boolean result = true;
      result = result && getDemo1List()
          .equals(other.getDemo1List());
      result = result && (getId()
          == other.getId());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getDemo1Count() > 0) {
        hash = (37 * hash) + DEMO1_FIELD_NUMBER;
        hash = (53 * hash) + getDemo1List().hashCode();
      }
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Demo2 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Demo2 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Demo2 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Demo2 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Demo2 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Demo2 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Demo2 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Demo2 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Demo2 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Demo2 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Demo2 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Demo2 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Demo2 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Demo2}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Demo2)
        Demo2OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtobufMessageDemo.internal_static_Demo2_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtobufMessageDemo.internal_static_Demo2_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Demo2.class, Builder.class);
      }

      // Construct using top.limitart.net.ProtobufMessageDemo.Demo2.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getDemo1FieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        if (demo1Builder_ == null) {
          demo1_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          demo1Builder_.clear();
        }
        id_ = 0;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtobufMessageDemo.internal_static_Demo2_descriptor;
      }

      @Override
      public Demo2 getDefaultInstanceForType() {
        return Demo2.getDefaultInstance();
      }

      @Override
      public Demo2 build() {
        Demo2 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Demo2 buildPartial() {
        Demo2 result = new Demo2(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (demo1Builder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            demo1_ = java.util.Collections.unmodifiableList(demo1_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.demo1_ = demo1_;
        } else {
          result.demo1_ = demo1Builder_.build();
        }
        result.id_ = id_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Demo2) {
          return mergeFrom((Demo2)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Demo2 other) {
        if (other == Demo2.getDefaultInstance()) return this;
        if (demo1Builder_ == null) {
          if (!other.demo1_.isEmpty()) {
            if (demo1_.isEmpty()) {
              demo1_ = other.demo1_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureDemo1IsMutable();
              demo1_.addAll(other.demo1_);
            }
            onChanged();
          }
        } else {
          if (!other.demo1_.isEmpty()) {
            if (demo1Builder_.isEmpty()) {
              demo1Builder_.dispose();
              demo1Builder_ = null;
              demo1_ = other.demo1_;
              bitField0_ = (bitField0_ & ~0x00000001);
              demo1Builder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getDemo1FieldBuilder() : null;
            } else {
              demo1Builder_.addAllMessages(other.demo1_);
            }
          }
        }
        if (other.getId() != 0) {
          setId(other.getId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Demo2 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Demo2) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<Demo1> demo1_ =
        java.util.Collections.emptyList();
      private void ensureDemo1IsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          demo1_ = new java.util.ArrayList<Demo1>(demo1_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          Demo1, Demo1.Builder, Demo1OrBuilder> demo1Builder_;

      /**
       * <code>repeated .Demo1 demo1 = 1;</code>
       */
      public java.util.List<Demo1> getDemo1List() {
        if (demo1Builder_ == null) {
          return java.util.Collections.unmodifiableList(demo1_);
        } else {
          return demo1Builder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Demo1 demo1 = 1;</code>
       */
      public int getDemo1Count() {
        if (demo1Builder_ == null) {
          return demo1_.size();
        } else {
          return demo1Builder_.getCount();
        }
      }
      /**
       * <code>repeated .Demo1 demo1 = 1;</code>
       */
      public Demo1 getDemo1(int index) {
        if (demo1Builder_ == null) {
          return demo1_.get(index);
        } else {
          return demo1Builder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Demo1 demo1 = 1;</code>
       */
      public Builder setDemo1(
          int index, Demo1 value) {
        if (demo1Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDemo1IsMutable();
          demo1_.set(index, value);
          onChanged();
        } else {
          demo1Builder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Demo1 demo1 = 1;</code>
       */
      public Builder setDemo1(
          int index, Demo1.Builder builderForValue) {
        if (demo1Builder_ == null) {
          ensureDemo1IsMutable();
          demo1_.set(index, builderForValue.build());
          onChanged();
        } else {
          demo1Builder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Demo1 demo1 = 1;</code>
       */
      public Builder addDemo1(Demo1 value) {
        if (demo1Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDemo1IsMutable();
          demo1_.add(value);
          onChanged();
        } else {
          demo1Builder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Demo1 demo1 = 1;</code>
       */
      public Builder addDemo1(
          int index, Demo1 value) {
        if (demo1Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDemo1IsMutable();
          demo1_.add(index, value);
          onChanged();
        } else {
          demo1Builder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Demo1 demo1 = 1;</code>
       */
      public Builder addDemo1(
          Demo1.Builder builderForValue) {
        if (demo1Builder_ == null) {
          ensureDemo1IsMutable();
          demo1_.add(builderForValue.build());
          onChanged();
        } else {
          demo1Builder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Demo1 demo1 = 1;</code>
       */
      public Builder addDemo1(
          int index, Demo1.Builder builderForValue) {
        if (demo1Builder_ == null) {
          ensureDemo1IsMutable();
          demo1_.add(index, builderForValue.build());
          onChanged();
        } else {
          demo1Builder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Demo1 demo1 = 1;</code>
       */
      public Builder addAllDemo1(
          Iterable<? extends Demo1> values) {
        if (demo1Builder_ == null) {
          ensureDemo1IsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, demo1_);
          onChanged();
        } else {
          demo1Builder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Demo1 demo1 = 1;</code>
       */
      public Builder clearDemo1() {
        if (demo1Builder_ == null) {
          demo1_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          demo1Builder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Demo1 demo1 = 1;</code>
       */
      public Builder removeDemo1(int index) {
        if (demo1Builder_ == null) {
          ensureDemo1IsMutable();
          demo1_.remove(index);
          onChanged();
        } else {
          demo1Builder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Demo1 demo1 = 1;</code>
       */
      public Demo1.Builder getDemo1Builder(
          int index) {
        return getDemo1FieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Demo1 demo1 = 1;</code>
       */
      public Demo1OrBuilder getDemo1OrBuilder(
          int index) {
        if (demo1Builder_ == null) {
          return demo1_.get(index);  } else {
          return demo1Builder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Demo1 demo1 = 1;</code>
       */
      public java.util.List<? extends Demo1OrBuilder>
           getDemo1OrBuilderList() {
        if (demo1Builder_ != null) {
          return demo1Builder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(demo1_);
        }
      }
      /**
       * <code>repeated .Demo1 demo1 = 1;</code>
       */
      public Demo1.Builder addDemo1Builder() {
        return getDemo1FieldBuilder().addBuilder(
            Demo1.getDefaultInstance());
      }
      /**
       * <code>repeated .Demo1 demo1 = 1;</code>
       */
      public Demo1.Builder addDemo1Builder(
          int index) {
        return getDemo1FieldBuilder().addBuilder(
            index, Demo1.getDefaultInstance());
      }
      /**
       * <code>repeated .Demo1 demo1 = 1;</code>
       */
      public java.util.List<Demo1.Builder>
           getDemo1BuilderList() {
        return getDemo1FieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          Demo1, Demo1.Builder, Demo1OrBuilder>
          getDemo1FieldBuilder() {
        if (demo1Builder_ == null) {
          demo1Builder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              Demo1, Demo1.Builder, Demo1OrBuilder>(
                  demo1_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          demo1_ = null;
        }
        return demo1Builder_;
      }

      private int id_ ;
      /**
       * <code>int32 id = 2;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 2;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 2;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Demo2)
    }

    // @@protoc_insertion_point(class_scope:Demo2)
    private static final Demo2 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Demo2();
    }

    public static Demo2 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Demo2>
        PARSER = new com.google.protobuf.AbstractParser<Demo2>() {
      @Override
      public Demo2 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Demo2(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Demo2> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Demo2> getParserForType() {
      return PARSER;
    }

    @Override
    public Demo2 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Demo1_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Demo1_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Demo2_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Demo2_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\017protobuf3.proto\"\025\n\005Demo1\022\014\n\004name\030\001 \001(\t" +
      "\"*\n\005Demo2\022\025\n\005demo1\030\001 \003(\0132\006.Demo1\022\n\n\002id\030\002" +
      " \001(\005B\'\n\020top.limitart.netB\023ProtobufMessag" +
      "eDemob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Demo1_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Demo1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Demo1_descriptor,
        new String[] { "Name", });
    internal_static_Demo2_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Demo2_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Demo2_descriptor,
        new String[] { "Demo1", "Id", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
